<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Health\V1;

use Thesis\Protobuf;
use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HealthListResponse
{
    /**
     * @param Protobuf\Map<string, \Thesis\Grpc\Health\V1\HealthCheckResponse> $statuses statuses contains all the services and their respective status.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\MapT(Reflection\StringT::T, new Reflection\ObjectT(\Thesis\Grpc\Health\V1\HealthCheckResponse::class)))]
        public Protobuf\Map $statuses = new Protobuf\Map(),
    ) {}
}
