<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Health\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HealthCheckResponse
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Thesis\Grpc\Health\V1\HealthCheckResponse\ServingStatus::class))]
        public \Thesis\Grpc\Health\V1\HealthCheckResponse\ServingStatus $status = \Thesis\Grpc\Health\V1\HealthCheckResponse\ServingStatus::UNKNOWN,
    ) {}
}
