<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1;

/**
 * @api
 */
final readonly class HealthListRequest {}
