<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HealthCheckRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $service = '',
    ) {}
}
