<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class HealthServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Grpc\Health\V1\HealthServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('grpc.health.v1.Health', [
            new Server\Rpc(
                handle: new Server\Handle('Check', \Grpc\Health\V1\HealthCheckRequest::class),
                handler: new Server\UnaryHandler($this->server->check(...)),
                type: Grpc\RpcType::Unary,
            ),
            new Server\Rpc(
                handle: new Server\Handle('List', \Grpc\Health\V1\HealthListRequest::class),
                handler: new Server\UnaryHandler($this->server->list(...)),
                type: Grpc\RpcType::Unary,
            ),
            new Server\Rpc(
                handle: new Server\Handle('Watch', \Grpc\Health\V1\HealthCheckRequest::class),
                handler: new Server\ServerStreamHandler($this->server->watch(...)),
                type: Grpc\RpcType::ServerStream,
            ),
        ]);
    }
}
