<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class HealthCheckResponse
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Grpc\Health\V1\HealthCheckResponse\ServingStatus::class))]
        public \Grpc\Health\V1\HealthCheckResponse\ServingStatus $status = \Grpc\Health\V1\HealthCheckResponse\ServingStatus::UNKNOWN,
    ) {}
}
