<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.3
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 *
 * Health is gRPC's mechanism for checking whether a server is able to handle
 * RPCs. Its semantics are documented in
 * https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
 */
final readonly class HealthClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Check gets the health of the specified service. If the requested service
     * is unknown, the call will fail with status NOT_FOUND. If the caller does
     * not specify a service name, the server should respond with its overall
     * health status.
     *
     * Clients should set a deadline when calling Check, and can declare the
     * server unhealthy if they do not receive a timely response.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function check(
        \Grpc\Health\V1\HealthCheckRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Grpc\Health\V1\HealthCheckResponse {
        /** @var Client\Invoke<\Grpc\Health\V1\HealthCheckRequest, \Grpc\Health\V1\HealthCheckResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/grpc.health.v1.Health/Check',
            output: \Grpc\Health\V1\HealthCheckResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * List provides a non-atomic snapshot of the health of all the available
     * services.
     *
     * The server may respond with a RESOURCE_EXHAUSTED error if too many services
     * exist.
     *
     * Clients should set a deadline when calling List, and can declare the server
     * unhealthy if they do not receive a timely response.
     *
     * Clients should keep in mind that the list of health services exposed by an
     * application can change over the lifetime of the process.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function list(
        \Grpc\Health\V1\HealthListRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Grpc\Health\V1\HealthListResponse {
        /** @var Client\Invoke<\Grpc\Health\V1\HealthListRequest, \Grpc\Health\V1\HealthListResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/grpc.health.v1.Health/List',
            output: \Grpc\Health\V1\HealthListResponse::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * Performs a watch for the serving status of the requested service.
     * The server will immediately send back a message indicating the current
     * serving status.  It will then subsequently send a new message whenever
     * the service's serving status changes.
     *
     * If the requested service is unknown when the call is received, the
     * server will send a message setting the serving status to
     * SERVICE_UNKNOWN but will *not* terminate the call.  If at some
     * future point, the serving status of the service becomes known, the
     * server will send a new message with the service's serving status.
     *
     * If the call terminates with status UNIMPLEMENTED, then clients
     * should assume this method is not supported and should not retry the
     * call.  If the call terminates with any other status (including OK),
     * clients should retry the call with appropriate exponential backoff.
     *
     * @return Client\ServerStreamChannel<\Grpc\Health\V1\HealthCheckRequest, \Grpc\Health\V1\HealthCheckResponse>
     */
    public function watch(
        \Grpc\Health\V1\HealthCheckRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\ServerStreamChannel {
        /** @var Client\Invoke<\Grpc\Health\V1\HealthCheckRequest, \Grpc\Health\V1\HealthCheckResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/grpc.health.v1.Health/Watch',
            output: \Grpc\Health\V1\HealthCheckResponse::class,
            type: Grpc\RpcType::ServerStream,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        $stream->send($request);
        $stream->close();

        return new Client\ServerStreamChannel($stream);
    }
}
