<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.11
 *   protoc               — v6.33.5
 * Source: grpc/health/v1/health.proto
 */

declare(strict_types=1);

namespace Grpc\Health\V1\HealthCheckResponse;

/**
 * @api
 */
enum ServingStatus: int
{
    case UNKNOWN = 0;
    case SERVING = 1;
    case NOT_SERVING = 2;

    /** Used only by the Watch method. */
    case SERVICE_UNKNOWN = 3;
}
